# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ois < Formula
  desc "Orchestrated Infrastructure Scaffolder - Generate production-ready Terraform for Cloud Infrastructure"
  homepage "https://github.com/NipulM/oisbase"
  version "0.2.2"

  on_macos do
    on_intel do
      url "https://github.com/NipulM/oisbase/releases/download/v0.2.2/oisbase_Darwin_x86_64.tar.gz"
      sha256 "9bb92f09a7b2015e397819036158f2e4804c614dd00d7b45d7af6d3caf94a7df"

      def install
        bin.install "ois"
      end
    end
    on_arm do
      url "https://github.com/NipulM/oisbase/releases/download/v0.2.2/oisbase_Darwin_arm64.tar.gz"
      sha256 "98fa86bb2452ee27a8264f3e7487cf8f79d582ed53311e8930c1f0f81fb1c8f8"

      def install
        bin.install "ois"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/NipulM/oisbase/releases/download/v0.2.2/oisbase_Linux_x86_64.tar.gz"
        sha256 "b8a95235417c83ec3c42b2cc8757960d6ade5699c387363d26ef1cc17f1d6246"

        def install
          bin.install "ois"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/NipulM/oisbase/releases/download/v0.2.2/oisbase_Linux_arm64.tar.gz"
        sha256 "7f4db643d59288d039a2cb04fca5d68e62c500e48ed8b9446c830ba5724d78e5"

        def install
          bin.install "ois"
        end
      end
    end
  end
end
