# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ois < Formula
  desc "Orchestrated Infrastructure Scaffolder - Generate production-ready Terraform for Cloud Infrastructure"
  homepage "https://github.com/NipulM/oisbase"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/NipulM/oisbase/releases/download/v0.1.0/oisbase_Darwin_x86_64.tar.gz"
      sha256 "210cafcb0892f7bcaba712782892ef6c80a2ffc5113e61967e7524367803b0c4"

      def install
        bin.install "ois"
      end
    end
    on_arm do
      url "https://github.com/NipulM/oisbase/releases/download/v0.1.0/oisbase_Darwin_arm64.tar.gz"
      sha256 "cfaf89c4ac2eb3b5ec4387f8682bdba5f4563ad38007c03afda20dc7ec5b3264"

      def install
        bin.install "ois"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/NipulM/oisbase/releases/download/v0.1.0/oisbase_Linux_x86_64.tar.gz"
        sha256 "7300dae95200e421facf80002b3aae653891f2e0fd1926364ae8c66fd1beaa0f"

        def install
          bin.install "ois"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/NipulM/oisbase/releases/download/v0.1.0/oisbase_Linux_arm64.tar.gz"
        sha256 "940ffc0d8b35408b545756b9edcf208e7c26432fbf26531e58802761954ef659"

        def install
          bin.install "ois"
        end
      end
    end
  end
end
